# Generated by Django 3.2.9 on 2021-11-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_prise_product_priсe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priсe',
            new_name='price',
        ),
    ]
